const initialState = {
    lessons: [
        {_id: "123", title: "Lesson 123"},
        {_id: "456", title: "Lesson 456"},
        {_id: "789", title: "Lesson 789"},
    ]
}

const lessonReducer = (state=initialState, action) => {
    switch (action.type) {
        case 'CREATE_LESSON':
            const newStateAfterCreate ={
                lessons: [
                    ...state.lessons,
                    {
                        title: "New Lesson",
                        _id: (new Date()).getTime() // TODO: remember to remove this line; id should be generated by server!
                    }
                ]
            }
            return newStateAfterCreate
        case 'DELETE_LESSON':
            return {
                lessons: state.lessons.filter(lesson => {
                    return lesson._id !== action.lessonToDelete._id;
                })
            }
        case 'UPDATE_LESSON':
        default:
            return state
    }
}

export default lessonReducer