const initialState = {
    modules: [
        {_id: 123, title: "Module 123"},
        {_id: 234, title: "Module 234"},
        {_id: 345, title: "Module 345"}
    ]
}

const moduleReducer = (state=initialState, action) => {
    switch (action.type) {
        case 'CREATE_MODULE':
            const newStateafterCreate ={
                modules: [
                    ...state.modules,
                    {
                        title: "New Module",
                        _id: (new Date()).getTime() // TODO: remember to remove this line; id should be generated by server!
                    }
                ]
            }
            return newStateafterCreate
        case 'DELETE_MODULE':
            const newStateAfterDelete = {
                modules: state.modules.filter(module => {
                    return module._id !== action.moduleToDelete._id;
                })
            }
            return newStateAfterDelete
        case 'UPDATE_MODULE':
        default:
            return state
    }
}

export default moduleReducer