const initialState = {
    modules: [
        {_id: 123, title: "Module 123"},
        {_id: 234, title: "Module 234"},
        {_id: 345, title: "Module 345"}
    ]
}

const moduleReducer = (state=initialState, action) => {
    switch (action.type) {
        case 'CREATE_MODULE':
            return {
                modules: [
                    ...state.modules,
                    {
                        title: "New Module",
                        _id: (new Date()).getTime() // TODO: remember to remove this line; id should be generated by server!
                    }
                ]
            }
        case 'DELETE_MODULE':
            return {
                modules: state.modules.filter(module => {
                    return module._id !== action.moduleToDelete._id;
                })
            }
        case 'UPDATE_MODULE':
            return {
                modules: state.modules.map(module => {
                    if(module._id === action.module._id) {
                        return action.module
                    } else {
                        return module
                    }
                })
            }
        case 'FIND_MODULES_FOR_COURSE':
            return {
                ...state,
                modules: action.modules
            }
        default:
            return state
    }
}

export default moduleReducer