const initialState = {
    topics: [
        {_id: "123", title: "Topic A"},
        {_id: "456", title: "Topic B"},
        {_id: "789", title: "Topic C"},
    ]
}

const topicReducer = (state=initialState, action) => {
    switch (action.type) {
        case 'CREATE_TOPIC':
            const newState ={
                topics: [
                    ...state.topics,
                    {
                        title: "New Topic",
                        _id: (new Date()).getTime() // TODO: remember to remove this line; id should be generated by server!
                    }
                ]
            }
            return newState
        case 'DELETE_TOPIC':
            return {
                topics: state.topics.filter(topic => {
                    return topic._id !== action.topicToDelete._id;
                })
            }
        case 'UPDATE_TOPIC':
        default:
            return state
    }
}

export default topicReducer